### PR TITLE
feat: Initial release of datadog_dio_interceptor plugin

### PR DESCRIPTION
**Pull request by a-h-mzd**
### What and why?

Currently there are no Dio interceptors in the repo. 

### How?

This PR aims to introduce a Dio interceptor to make it easier for anyone using the Dio package to attach Datadog-specific headers to the requests.

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [ ] This pull request references a Github or JIRA issue

### CODE REVIEW

**Comment by a-h-mzd** [comment]
@fuzzybinary, currently there are no tests implemented for this package. I plan to add the tests soon.

**Comment by rtrieu** [comment]
Created DOCS-9428 for docs review.

**Comment by fuzzybinary** [comment]
@rtrieu Hold off on docs review until I can take a look at the code.

**Comment by fuzzybinary** [comment]
Hi @a-h-mzd,

We'll need tests before we can accept, but, also, is there a reason this was needed? All cases I've seen of Dio either use the default `HttpClient` provided with `HttpOverrides`, or accept a `Client` from the `http` package.  Our interceptor provides ways to override both.

Is there a case I don't know of where Dio will not use something we already intercept, or is there additional functionality this would provide?

**Comment by a-h-mzd** [comment]
Hi @fuzzybinary,

You're partially correct. Dio for native uses the default client provided by the overrides, but Dio for browser takes a different approach and uses `XMLHttpRequest` directly to make the requests. As far as I know, this is done to ensure that the UI thread does not freeze, no matter how heavy and time-consuming the API call is.

And as for tests, I will try to write some as soon as I get the chance.

**Comment by fuzzybinary** [comment]
@a-h-mzd Did you double check that the Browser SDK doesn't already intercept these without going through any Dart / Flutter code? If I remember correctly, it intercepts all XMLHttpRequests by default (and gets more information out of them than we do). If it doesn't that may be the real bug, not the lack of a Dio interceptor.

I appreciate the contributions, but I would always start with an issue in the repo first. Show what you want to do and the fact that it doesn't work, then we can work together to determine what the solution should be (which, in reality, may be this interceptor provided your issue checks out).

**Comment by a-h-mzd** [comment]
@fuzzybinary that is a good point. I will create an issue right away.

**Comment by a-h-mzd** [comment]
@fuzzybinary thank you for your support on [this issue](https://github.com/DataDog/dd-sdk-flutter/issues/663). Do you think it’s worth to keep this PR open?

**Comment by fuzzybinary** [comment]
No I think it's better to close it. Our support for Dio flows through HttpOverrides at the moment.

**Pull request closed without merging**
